// Code generated by mdatagen. DO NOT EDIT.

package varnishcachelogreceiver

import (
	"os"
	"testing"
)

func TestMain(m *testing.M) {
	// skipping goleak test as per metadata.yml configuration
	os.Exit(m.Run())
}
