services:
  varnish:
    image: varnish:9.0.3
    ports:
      - "8080:8080"
    volumes:
      - ./dev/varnish/etc/varnish:/etc/varnish
      - ./dev/varnish/var/www/html:/var/www/html
      - ./data/var/lib/varnish:/var/lib/varnish
    environment:
      VARNISH_HTTP_PORT: "8080"
      VARNISH_SIZE: "1G"

  otel:
    image: grafana/otel-lgtm:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ORG_ROLE=Editor
      - GF_AUTH_ORG_NAME=Main Org.
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Admin
    ports:
      - "3000:3000" # grafana
      - "4317:4317" # otlp http/json
      - "4318:4318" # otlp grpc
      - "4040:4040" # pyroscope