---
name: varnishotelcollector

volumes:
  varnish-vsm:

services:
  varnish:
    image: varnish:9.0.3-3
    ports:
      - "8080:8080"
    volumes:
      - ./hack/varnish/etc/varnish:/etc/varnish
      - ./hack/varnish/var/www/html:/var/www/html
      - varnish-vsm:/var/lib/varnish/varnishd
    environment:
      VARNISH_HTTP_PORT: "8080"
      VARNISH_SIZE: "1G"

  varnishotelcollector:
    build:
      dockerfile: distribution/varnishotelcollector/Dockerfile
      context: .
      args:
        - VARNISH_VERSION=9.0.3-3
    ports:
      - "4444:4444" # prometheus
    volumes:
      - varnish-vsm:/var/lib/varnish/varnishd
      - ./distribution/varnishotelcollector/config.yaml:/etc/varnishotelcollector/config.yaml:ro
    environment:
      OTEL_GRPC_ENDPOINT: "otel:4317"

  otel:
    image: grafana/otel-lgtm:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ORG_ROLE=Editor
      - GF_AUTH_ORG_NAME=Main Org.
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Admin
    ports:
      - "3000:3000" # grafana
      - "4317:4317" # otlp http/json
      - "4318:4318" # otlp grpc
      - "4040:4040" # pyroscope