receivers:
  varnishcachestat:
    collection_interval: 10s
  varnishcachelog: {}

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlp_grpc:
    endpoint: "0.0.0.0:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:4444"
    enable_open_metrics: true
    translation_strategy: "UnderscoreEscapingWithoutSuffixes"
    without_scope_info: true # removes otel_* labels in Prometheus HTTP output
    resource_to_telemetry_conversion:
      enabled: true
    namespace: varnish

service:
  pipelines:
    metrics:
      receivers: [ varnishcachestat ]
      processors: [ ]
      exporters: [ prometheus ]
    traces:
      receivers: [ varnishcachelog ]
      processors: [ ]
      exporters: [ debug ]
