// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/featuregate"
)

var ReceiverVarnishcachestatBreakPrometheusExporterCompatFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"receiver.varnishcachestat.breakPrometheusExporterCompat",
	featuregate.StageAlpha,
	featuregate.WithRegisterDescription("Break compatibility with prometheus_varnish_exporter for metrics"),
	featuregate.WithRegisterReferenceURL("https://github.com/thomasklinger1234/varnishotelcollector/issues/7"),
	featuregate.WithRegisterFromVersion("v0.0.0"),
)
