// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/varnishcachestat component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("varnishcachestat")
	ScopeName = "github.com/thomasklinger1234/varnishotelcollector/receiver/varnishcachestatreceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
