// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/varnishcachelog component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("varnishcachelog")
	ScopeName = "github.com/thomasklinger1234/varnishotelcollector/receiver/varnishcachelogreceiver"
)

const (
	TracesStability = component.StabilityLevelDevelopment
)
