---
name: global_pullrequest_actionlint

on:
  pull_request:
    branches:
      - main
      - next
    paths:
      - '.github/workflows/**'

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: '0'
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: info
          reporter: 'github-pr-review'
          fail_on_error: true